### ISSUE TITLE
0.0.3版本与莱特兰背包冲突

### ISSUE THREAD

**Issue by Dr-WeiAL** [XiaoHuNao/MineTeam#2]
https://modrinth.com/mod/l2backpack

[crash-2024-09-25_13.07.31-client.txt](https://github.com/user-attachments/files/17125311/crash-2024-09-25_13.07.31-client.txt)
0.0.1和0.0.2测试没问题，更新到0.0.3崩溃

**Comment by lcy0x1** [comment]
我是莱特兰背包作者，我处理了

**Comment by XiaoHuNao** [comment]
> 我是莱特兰背包作者，我处理了

十分感谢
